### ISSUE TITLE
Stats array configuration leads to error with non existing keys

### ISSUE THREAD

**Issue by metatron23** [roele/istats.widget#29]
I have tried to install the updated version and I get this error (see picture).
![Screenshot 2019-08-18 at 17 51 24](https://user-images.githubusercontent.com/10022028/63226949-1ecc0400-c1e1-11e9-9830-9262b83ed0e0.png)

Reinstalling didn't help.

**Comment by roele** [comment]
@metatron23 Please provide more information (Hardware, macOS version, ... ) and possibly the output of `istats` command from your command line.

**Comment by metatron23** [comment]
Completely forgot to add that, sorry.
iMac 27" 2019, macOS Catalina 
<img width="464" alt="Screenshot 2019-08-18 at 18 47 07" src="https://user-images.githubusercontent.com/10022028/63227620-99e4e880-c1e8-11e9-9453-20a0729d2221.png">

You need some extra info?

**Comment by roele** [comment]
Okey it looks like your hardware only provides one fan whereas by default the widget expects two (MacBook Pro default). If you remove the `fan-1` entry in `config.stats` property, the error should be gone.

I'll see if i can somehow fix the code to check the data as opposed to blindly insert what might be configured.

**Comment by metatron23** [comment]
I have tried to remove fan-1, but that didn't help.
<img width="475" alt="Screenshot 2019-08-18 at 19 16 41" src="https://user-images.githubusercontent.com/10022028/63227966-ca2e8600-c1ec-11e9-9193-16270d80d16d.png">

any suggestion?

**Comment by roele** [comment]
Remaining entry should be `fan-0` as fans are indexed starting with `0` (also see `istats` output referring to `Fan 0 speed`).

**Comment by metatron23** [comment]
When I changed to fan-0, I got this error

![Screenshot 2019-08-18 at 20 13 30](https://user-images.githubusercontent.com/10022028/63228546-bc7cfe80-c1f4-11e9-8364-73c949108c8f.png)

**Comment by roele** [comment]
Which makes total sense as `istats` reports `No battery on system`. So the only things you can display are `cpu` and `fan-0` in your case.

```
...
stats: ['cpu', 'fan-0']
...
```

**Comment by roele** [comment]
Fixed with 54c0fd5

**Comment by metatron23** [comment]
still doesn't work (nothing displays), but at least there is no error message.

**Comment by roele** [comment]
I am not aware of any issues related to Catalina yet but might well be that there are some.

Other widgets work properly?
Does the debugger show the stats elements injected in the HTML?

**Comment by metatron23** [comment]
Other widgets works fine.

I never used Web Inspector, so I don't know what exactly do you need from Debugger.

**Comment by roele** [comment]
Hard to tell why i does not show anything for you (position, missing css, other issue,...). The `Elements` tab of the Web Inspector can give some insights on the rendered HTML and might reveal the issue.

<img width="1230" alt="Screenshot 2019-08-19 at 19 13 06" src="https://user-images.githubusercontent.com/181773/63285242-9cf9da80-c2b5-11e9-877b-41c7e6f7adad.png">

**Comment by metatron23** [comment]
Strangely enought after reinstalling it for couple of times the widget appears :)
Is there a way to add GPU there as well? In previous version it was possible to do that (helped me a lot to see GPU temperature).

**Comment by roele** [comment]
GPU support is on the roadmap (see #23). Previous versions do not support this either. What istats key would the GPU be on your hardware (`TCGC`, `TG0P`, ...)?

**Comment by metatron23** [comment]
istats shows this 
<img width="320" alt="Screenshot 2019-08-19 at 21 20 32" src="https://user-images.githubusercontent.com/10022028/63292982-37164e80-c2c7-11e9-940d-ec3395ee22e8.png">

But I had GPU on last version that I used on old mac (had lots of trouble to get the icon I remember) or is this something else that was showing?
<img width="727" alt="Screenshot 2019-08-19 at 21 22 51" src="https://user-images.githubusercontent.com/10022028/63293126-92e0d780-c2c7-11e9-91ac-f0a7820a59d9.png">

**Comment by roele** [comment]
You might have used a fork or extended it yourself but version [1.2.0](https://github.com/roele/istats.widget/blob/istats.widget-1.2.0/istats.widget/index.js) did not ship with GPU support out of the box.

Thanks for the screenshot will consider making the key configurable with #23.
